name: Testing

on: [push, pull_request]

jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django
          # If you have a requirements.txt file, you can use the following command instead
          # pip install -r requirements.txt

      - name: Run Django migrations
        run: python manage.py migrate

      - name: Run Django unit tests
        run: python manage.py test

